# Generated by update-python-packages.py v6.0.2 — do not edit by hand.
#
# Pins are resolved from
#   tools/requirements/requirements.core.txt @ v6.0.2
#   https://dl.espressif.com/dl/esp-idf/espidf.constraints.v6.0.txt
# plus per-package metadata (dependencies, sdist hashes) from PyPI.
{
  fetchPypi,
  fetchurl,
  pythonPackages,
}:
with pythonPackages;
rec {
  idf-component-manager = buildPythonPackage rec {
    pname = "idf-component-manager";
    version = "3.0.3";
    pyproject = true;

    build-system = [
      setuptools
    ];

    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/86/4b/4fd210417a4c16ec3da56d4143ffe3503fe77f6791ee299f02114d708340/idf_component_manager-3.0.3.tar.gz";
      sha256 = "sha256-UU8T9fx/Ssl0+wtD0wQq7Y9zjxkhnaXUDPZ/ibrVX0c=";
    };

    doCheck = false;

    propagatedBuildInputs = [
      psutil
      click
      colorama
      pyparsing
      ruamel-yaml
      requests
      requests-file
      requests-toolbelt
      tqdm
      jsonref
      pydantic
      pydantic-core
      pydantic-settings
      truststore
    ];

    meta = {
      homepage = "https://pypi.org/project/idf-component-manager/";
    };
  };

  esp-coredump = buildPythonPackage rec {
    pname = "esp-coredump";
    version = "1.14.0";
    pyproject = true;

    build-system = [
      setuptools
    ];

    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/63/79/d12086a400526fa4b078c7e9963e06b2297c2345d4931497ff836e064454/esp_coredump-1.14.0.tar.gz";
      sha256 = "sha256-HDqIHObATfq408mDzpN8WQDIQxfpZFnK2L+LWEcrhzs=";
    };

    doCheck = false;

    propagatedBuildInputs = [
      construct
      pygdbmi
      esptool
    ];

    meta = {
      homepage = "https://pypi.org/project/esp-coredump/";
    };
  };

  esptool = buildPythonPackage rec {
    pname = "esptool";
    version = "5.3.1";
    pyproject = true;

    build-system = [
      setuptools
    ];

    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/ac/d2016cf6b3709d0e0166f45f84bc6e2d717757b5f59020ccb34de08d1b9b/esptool-5.3.1.tar.gz";
      sha256 = "sha256-EleB825qLQjEhFJKRfNAaUZ1Note7q2dDLIbIDSpHZg=";
    };

    doCheck = false;

    propagatedBuildInputs = [
      bitstring
      cryptography
      pyserial
      reedsolo
      pyyaml
      intelhex
      rich-click
      click
    ];

    meta = {
      homepage = "https://pypi.org/project/esptool/";
    };
  };

  esp-idf-kconfig = buildPythonPackage rec {
    pname = "esp-idf-kconfig";
    version = "3.12.0";
    pyproject = true;

    build-system = [
      setuptools
    ];

    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/a8/ffa689bd9b360cfe559e5796bc1c750ebb500c53d855c80f47862a373afd/esp_idf_kconfig-3.12.0.tar.gz";
      sha256 = "sha256-oKvXk6PocshqsKN85UQtWPnl0wNtZBld9/VW14e8/JU=";
    };

    doCheck = false;

    propagatedBuildInputs = [
      esp-pylib
      pyparsing
      textual
      intelhex
      rich
    ];

    meta = {
      homepage = "https://pypi.org/project/esp-idf-kconfig/";
    };
  };

  esp-idf-monitor = buildPythonPackage rec {
    pname = "esp-idf-monitor";
    version = "1.9.0";
    pyproject = true;

    build-system = [
      setuptools
    ];

    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7c/86/64a8984759506fbbbfce14ec981ec736420aeb79ffc964166a507e3be065/esp_idf_monitor-1.9.0.tar.gz";
      sha256 = "sha256-DDjaDD04PUtjBYY7jfjqbgkwOtWm1bqSznGzHxz3AM4=";
    };

    doCheck = false;

    propagatedBuildInputs = [
      pyserial
      esp-coredump
      esp-idf-panic-decoder
      pyelftools
    ];

    meta = {
      homepage = "https://pypi.org/project/esp-idf-monitor/";
    };
  };

  esp-idf-nvs-partition-gen = buildPythonPackage rec {
    pname = "esp-idf-nvs-partition-gen";
    version = "0.1.9";
    pyproject = true;

    build-system = [
      setuptools
    ];

    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7b/78/572dcca160714a4e60bee0db591f327c63df3bad3ecda22b410ed8ea5299/esp_idf_nvs_partition_gen-0.1.9.tar.gz";
      sha256 = "sha256-Q6ObVLJDGJ6REJpOmZaMhk8y4g4Ne5wzBSu9JqXxaQ8=";
    };

    doCheck = false;

    propagatedBuildInputs = [
      cryptography
    ];

    meta = {
      homepage = "https://pypi.org/project/esp-idf-nvs-partition-gen/";
    };
  };

  esp-idf-diag = buildPythonPackage {
    pname = "esp-idf-diag";
    version = "0.2.0";
    pyproject = true;

    src = fetchurl {
      url = "https://github.com/espressif/esp-idf-diag/archive/refs/tags/v0.2.0.tar.gz";
      sha256 = "sha256-YEwLBYOveUl1xmZeZScXzY98PLCEWGgomt3t1WjJPJQ=";
    };

    build-system = [
      setuptools
    ];

    doCheck = false;

    propagatedBuildInputs = [
      pyyaml
      rich
    ];

    meta = {
      homepage = "https://github.com/espressif/esp-idf-diag";
    };
  };

  esp-idf-panic-decoder = buildPythonPackage rec {
    pname = "esp-idf-panic-decoder";
    version = "1.5.0";
    pyproject = true;

    build-system = [
      setuptools
    ];

    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/da/f1/e4d6170a51e15afd27660992fbd2a4728cf401750ebb388b1ce035d95025/esp_idf_panic_decoder-1.5.0.tar.gz";
      sha256 = "sha256-ewk/ehul/f135CqWBIe1pDP2Dc2r84zJgXbykfw6iPs=";
    };

    doCheck = false;

    propagatedBuildInputs = [
      pyelftools
      pyparsing
    ];

    meta = {
      homepage = "https://pypi.org/project/esp-idf-panic-decoder/";
    };
  };

  pyclang = buildPythonPackage rec {
    pname = "pyclang";
    version = "0.7.0";
    pyproject = true;

    build-system = [
      setuptools
    ];

    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/ec/8b6c6bcf9d518225c682116c75331cab0c2cca00dcb0793ffd21bba7300d/pyclang-0.7.0.tar.gz";
      sha256 = "sha256-s9SHh7tnSJFk0G7wNDMo1lGDG0Xw62fg/skiHvompfU=";
    };

    doCheck = false;

    propagatedBuildInputs = [
      esp-pylib
      rich
    ];

    meta = {
      homepage = "https://pypi.org/project/pyclang/";
    };
  };

  freertos_gdb = buildPythonPackage rec {
    pname = "freertos-gdb";
    version = "1.0.4";
    pyproject = true;

    build-system = [
      setuptools
    ];

    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/10/6c/656c7e3df6ae38cc456d780889304c9d77cebb7a1b9401314d668b5ef564/freertos-gdb-1.0.4.tar.gz";
      sha256 = "sha256-lH/dlTX2PuZ89rX5zzpedHkqHvdVy+h6BzJ8rVFmkb8=";
    };

    doCheck = false;

    meta = {
      homepage = "https://pypi.org/project/freertos-gdb/";
    };
  };

  esp-pylib = buildPythonPackage rec {
    pname = "esp-pylib";
    version = "1.1.3";
    pyproject = true;

    build-system = [
      setuptools
    ];

    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/30/f5/d20da398b9a18315bec41f50c5fd84f3bceef6914df06f545160318e8691/esp_pylib-1.1.3.tar.gz";
      sha256 = "sha256-p/Hiqf8oNnivrsb9Yl2lnGiuSNZ3ABpnkj9eUIoXx+g=";
    };

    doCheck = false;

    propagatedBuildInputs = [
      rich
    ];

    meta = {
      homepage = "https://pypi.org/project/esp-pylib/";
    };
  };

}
